AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'exe/**/*'
    - 'vendor/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'ai_git_commit.gemspec'
